config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :listings
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :location
  has_one :listing_property_kind
  has_one :property_kind, through: :listing_property_kind
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :beds, :baths, :plus, :rating, :price, :rental_period, :main_image_caption, :location_id)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :beds, class: 'form-label' %>
      <%= form.number_field :beds, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :baths, class: 'form-label' %>
      <%= form.number_field :baths, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :plus, class: 'form-label' %>
      <%= form.check_box :plus, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :rating, class: 'form-label' %>
      <%= form.number_field :rating, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :price, class: 'form-label' %>
      <%= form.number_field :price, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :rental_period, class: 'form-label' %>
      <%= form.text_field :rental_period, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :main_image_caption, class: 'form-label' %>
      <%= form.text_field :main_image_caption, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :location_id, class: 'form-label' %>
      <%= form.text_field :location_id, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if listing.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', listing, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if listing.persisted? %>
      <%= link_to "Cancel", listing, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", listings_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p>
    <strong>Title:</strong>
    <%= listing.title %>
  </p>

  <p>
    <strong>Beds:</strong>
    <%= listing.beds %>
  </p>

  <p>
    <strong>Baths:</strong>
    <%= listing.baths %>
  </p>

  <p>
    <strong>Plus:</strong>
    <%= listing.plus %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= listing.rating %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= listing.price %>
  </p>

  <p>
    <strong>Rental period:</strong>
    <%= listing.rental_period %>
  </p>

  <p>
    <strong>Main image caption:</strong>
    <%= listing.main_image_caption %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= listing.location_id %>
  </p>

</div>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'form', listing: @listing %>

app/views/listings/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Listings</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_listing_path, class: 'btn btn-primary' do %>
    Add New Listing
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Beds</th>
            <th>Baths</th>
            <th>Plus</th>
            <th>Rating</th>
            <th>Price</th>
            <th>Rental period</th>
            <th>Main image caption</th>
            <th>Location</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @listings.each do |listing| %>
        <%= content_tag :tr, id: dom_id(listing), class: dom_class(listing) do %>
          

                      <td><%= listing.title %></td>
                      <td><%= listing.beds %></td>
                      <td><%= listing.baths %></td>
                      <td><%= listing.plus %></td>
                      <td><%= listing.rating %></td>
                      <td><%= listing.price %></td>
                      <td><%= listing.rental_period %></td>
                      <td><%= listing.main_image_caption %></td>
                      <td><%= listing.location %></td>
          
          
            <td><%= link_to 'Show', listing %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form', listing: @listing %>

app/views/listings/show.html.erb
<div class="page-header">
  <%= link_to listings_path, class: 'btn btn-default' do %>
    All Listings
  <% end %>
  <%= link_to edit_listing_path(@listing), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show listing</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @listing.title %></dd>
  <dt>Beds:</dt>
  <dd><%= @listing.beds %></dd>
  <dt>Baths:</dt>
  <dd><%= @listing.baths %></dd>
  <dt>Plus:</dt>
  <dd><%= @listing.plus %></dd>
  <dt>Rating:</dt>
  <dd><%= @listing.rating %></dd>
  <dt>Price:</dt>
  <dd><%= @listing.price %></dd>
  <dt>Rental period:</dt>
  <dd><%= @listing.rental_period %></dd>
  <dt>Main image caption:</dt>
  <dd><%= @listing.main_image_caption %></dd>
  <dt>Location:</dt>
  <dd><%= @listing.location %></dd>
</dl>